default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  port: 5005
  username: demo
  password: 123456

development:
  <<: *default
  database: rails_demo_1_development
  password: 123456

test:
  <<: *default
  database: rails_demo_1_test
  password: 123456

production:
  <<: *default
  database: rails_demo_1_production
  username: rails_demo_1
  password: <%= ENV['RAILS_DEMO_1_DATABASE_PASSWORD'] %>
